### PR TITLE
Feature/animations

### PR DESCRIPTION
**Pull request by skvale**
This isn't a finished PR, but I still wanted to open it to bring up a discussion.

If you were to use `List (Svg.Attribute msg)` as the `Style` [113](https://github.com/terezka/elm-plot/blob/master/src/Plot.elm#L113) instead of `List (String, String)` you would get more control over the behavior.

As an example, [skvale.github.io](https://skvale.github.io) shows animating the scatter chart from #20.  Just hover over a dot.

An added benefit is `Svg.Event` returns an `Svg.Attribute msg` so you can add those to the "Style" as well.

### CODE REVIEW

**Comment by terezka** [comment]
Yeah, that's a great idea! I've been thinking of it too. Maybe just opening up the possibility to add all the custom SVG attributes you want. I'm adding interactivity and splitting the code right now, so I'll get going on this asap (unless you beat me to it!).

**Comment by hkjels** [comment]
All Svg attributes sounds great! I would like to add a little glow-effect to a line-chart, but as far as I can see, that's not really possible at the moment.

**Comment by terezka** [comment]
@hkjels It will be possible in the next version! 🙌

**Comment by skvale** [comment]
@terezka Cool. Feel free to use this PR, close it, or suggest a different direction.

@hkjels I'm curious how you would add a glow affect to the line chart with `Svg.Attributes`.  I needed to add an `Svg.filter` element within the plot's `svg` tag.

**Pull request closed without merging**
